version: '3'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 5000
    ports:
      - 8080:5000
    restart: always

